In [9]:
import sys
import numpy as np
import matplotlib.pyplot as plt

In [5]:
Xtrain, ytrain, Xtest, ytest = np.load('mnist_scaled.npz').values()

In [8]:
Xtrain.shape, ytrain.shape, Xtest.shape, ytest.shape

((60000, 784), (60000,), (10000, 784), (10000,))

In [14]:
bias = np.ones((Xtrain.shape[0], 1))
np.c_[bias, Xtrain]

array([[ 1., -1., -1., ..., -1., -1., -1.],
       [ 1., -1., -1., ..., -1., -1., -1.],
       [ 1., -1., -1., ..., -1., -1., -1.],
       ...,
       [ 1., -1., -1., ..., -1., -1., -1.],
       [ 1., -1., -1., ..., -1., -1., -1.],
       [ 1., -1., -1., ..., -1., -1., -1.]])

In [26]:
from sklearn.preprocessing import OneHotEncoder

In [41]:
y = np.array([0, 1, 2, 0, 2, 1, 0, 2]).reshape(-1, 1)
y = OneHotEncoder().fit_transform(y).toarray()

In [43]:
k = np.random.normal(size=y.shape)

In [52]:
y * k

array([[ 1.74674023, -0.        ,  0.        ],
       [-0.        ,  0.20075361, -0.        ],
       [-0.        , -0.        , -1.24809698],
       [ 1.23182103, -0.        , -0.        ],
       [-0.        , -0.        , -0.51522125],
       [-0.        , -1.17856005,  0.        ],
       [ 2.40624984, -0.        ,  0.        ],
       [ 0.        ,  0.        , -0.77423428]])

In [57]:
y

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.]])

In [56]:
np.argmax(y, axis=1)

array([0, 1, 2, 0, 2, 1, 0, 2], dtype=int64)

In [58]:
y

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.]])

In [22]:
y = np.array([0, 1, 0])
- y * np.log([0.05, 0.80, 0.15])

array([-0.        ,  0.22314355, -0.        ])

In [ ]:
class NeuralNetMLP(object):
    